# Generated by Django 6.0.6 on 2026-06-10 04:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloRol",
            fields=[
                ("Estado", models.BooleanField(db_column="Estado", default=True)),
                (
                    "Fecha_Creacion",
                    models.DateTimeField(auto_now_add=True, db_column="Fecha_Creacion"),
                ),
                (
                    "Fecha_Actualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="Fecha_Actualizacion"
                    ),
                ),
                (
                    "Id",
                    models.AutoField(
                        db_column="Id_Rol", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(
                        db_column="Nombre_Rol", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "Rol",
            },
        ),
        migrations.CreateModel(
            name="ModeloTipoIdentificacion",
            fields=[
                ("Estado", models.BooleanField(db_column="Estado", default=True)),
                (
                    "Fecha_Creacion",
                    models.DateTimeField(auto_now_add=True, db_column="Fecha_Creacion"),
                ),
                (
                    "Fecha_Actualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="Fecha_Actualizacion"
                    ),
                ),
                (
                    "Id",
                    models.AutoField(
                        db_column="Id_TipoIdentificacion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(
                        db_column="Nombre_TipoIdentificacion",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "Abreviatura",
                    models.CharField(
                        db_column="Abreviatura_TipoIdentificacion",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Identificación",
                "verbose_name_plural": "Tipos de Identificación",
                "db_table": "Tipo_Identificacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ModeloUsuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("Estado", models.BooleanField(db_column="Estado", default=True)),
                (
                    "Fecha_Creacion",
                    models.DateTimeField(auto_now_add=True, db_column="Fecha_Creacion"),
                ),
                (
                    "Fecha_Actualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="Fecha_Actualizacion"
                    ),
                ),
                (
                    "Id",
                    models.AutoField(
                        db_column="Id_Usuario", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(db_column="Nombre_Usuario", max_length=100),
                ),
                (
                    "Apellido",
                    models.CharField(db_column="Apellido_Usuario", max_length=100),
                ),
                (
                    "Telefono",
                    models.CharField(db_column="Telefono_Usuario", max_length=20),
                ),
                (
                    "NumeroIdentificacion",
                    models.CharField(
                        db_column="NumeroIdentificacion_Usuario",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "Correo",
                    models.EmailField(
                        db_column="Correo_Usuario", max_length=100, unique=True
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "Tipo_Identificacion",
                    models.ForeignKey(
                        db_column="Tipo_Identificacion_Usuario",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="APLICACION_USUARIOS.modelotipoidentificacion",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "Usuario",
            },
            managers=[
                ("Objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ModeloRolUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Estado", models.BooleanField(db_column="Estado", default=True)),
                (
                    "Fecha_Creacion",
                    models.DateTimeField(auto_now_add=True, db_column="Fecha_Creacion"),
                ),
                (
                    "Fecha_Actualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="Fecha_Actualizacion"
                    ),
                ),
                (
                    "Rol",
                    models.ForeignKey(
                        db_column="Rol_RolUsuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APLICACION_USUARIOS.modelorol",
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        db_column="Usuario_RolUsuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Rol_Usuario",
                "unique_together": {("Usuario", "Rol")},
            },
        ),
    ]
