# Generated by Django 6.0.6 on 2026-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION_USUARIOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelousuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='modelorolusuario',
            name='id',
        ),
        migrations.AddField(
            model_name='modelorolusuario',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
